baseURL: "https://blog.hllstr.com"
languageCode: "en-us"
# title: "mike-seagull blog"
theme: "PaperMod"
params:
  defaultTheme: auto
  disableThemeToggle: true
  env: production
  homeInfoParams:
    Title: Mike Hollister
    Content: Software Engineer - Applications and DevOps
  socialIcons:
    - name: github
      url: https://github.com/mike-seagull
    - name: linkedin
      url: https://www.linkedin.com/in/mike-hollister
